[package]
name = "eccat"
version = "0.1.1"
edition = "2021"
authors = ["skycloudd"]

[dependencies]
chrono = "0.4.38"
cozy-chess = { version = "0.3.4", features = ["std"] }
crossbeam-channel = "0.5.12"
tikv-jemallocator = "0.5.4"
vampirc-uci = "0.11.1"

[profile.full]
inherits = "release"
codegen-units = 1
lto = "fat"
