[package]
name = "eccat"
version = "0.2.0"
edition = "2021"
authors = ["skycloudd"]

[dependencies]
assert_size = "0.1.1"
chrono = { version = "0.4.38", default-features = false }
const-str = { version = "0.5.7", features = ["proc"] }
cozy-chess = "0.3.4"
crossbeam-channel = "0.5.12"
pdqsort = "1.0.3"
vampirc-uci = "0.11.1"

[target.'cfg(not(windows))'.dependencies]
tikv-jemallocator = "0.5.4"

[profile.full]
inherits = "release"
codegen-units = 1
lto = "fat"

[features]
pext = ["cozy-chess/pext"]

[build-dependencies]
anyhow = "1.0.83"
vergen = { version = "8.3.1", features = [
    "build",
    "git",
    "gitcl",
    "rustc",
    "si",
] }
