[package]
name = "eccat"
version = "0.1.2"
edition = "2021"
authors = ["skycloudd"]

[dependencies]
assert_size = "0.1.1"
chrono = "0.4.38"
cozy-chess = { version = "0.3.4", features = ["std"] }
crossbeam-channel = "0.5.12"
pdqsort = "1.0.3"
rand = "0.8.5"
tikv-jemallocator = "0.5.4"
vampirc-uci = "0.11.1"

[profile.full]
inherits = "release"
codegen-units = 1
lto = "fat"

[features]
pext = ["cozy-chess/pext"]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "evaluate"
harness = false

[[bench]]
name = "movegen"
harness = false
