[package]
name = "eccat"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.37"
cozy-chess = { version = "0.3.3", features = [
    "std",
], git = "https://github.com/skycloudd/cozy-chess.git" }
crossbeam-channel = "0.5.12"
vampirc-uci = "0.11.1"
