name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                toolchain: [stable, beta, nightly]

        name:
            Run `cargo build/test` on ${{ matrix.os }} with Rust
            ${{matrix.toolchain }}
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              run:
                  rustup toolchain install ${{matrix.toolchain}} --profile
                  minimal --no-self-update

            - name: Install cargo-hack
              uses: taiki-e/install-action@cargo-hack

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2

            - name: Build
              run: cargo build --verbose

            - name: Run tests
              run: cargo test --verbose

            - name: Check feature powerset
              run: cargo hack check --feature-powerset --no-dev-deps --skip pext
